spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pasetodb
    username: dev
    password: qwerty
    driver-class-name: org.postgresql.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
     # hibernate.jdbc.time_zone: UTC
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql.init.mode: always